theme = "gruvbox"

[editor]
line-number = "relative"
true-color = true
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
mouse = false
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
j = { k = "normal_mode" }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
